CREATE TABLE [dbo].[SF_ZH_QuestionRecord](
	[Id] [uniqueidentifier] NOT NULL,
	[Code] [nvarchar](50) NULL,
	[Title] [nvarchar](200) NULL,
	[Sender] [nvarchar](20) NULL,
	[SenderId] [uniqueidentifier] NULL,
	[SenderDept] [nvarchar](100) NULL,
	[SenderDeptId] [uniqueidentifier] NULL,
	[IsAlreadyReply] [int] NULL,
	[ReplyContactId] [uniqueidentifier] NULL,
	[UpdHumId] [uniqueidentifier] NULL,
	[UpdHumName] [nvarchar](80) NULL,
	[UpdDate] [datetime] NULL,
	[RegDate] [datetime] NULL,
	[RegHumName] [nvarchar](80) NULL,
	[RegHumId] [uniqueidentifier] NULL,
	[OwnProjName] [nvarchar](255) NULL,
	[OwnProjId] [uniqueidentifier] NULL,
	[EpsProjId] [uniqueidentifier] NULL,
	[ApprHumId] [uniqueidentifier] NULL,
	[ApprHumName] [nvarchar](80) NULL,
	[ApprDate] [datetime] NULL,
	[Status] [tinyint] NULL,
	[Memo] [nvarchar](4000) NULL,
	Questions nvarchar(4000) null,
	MenuName nvarchar(200) null
)