CREATE TABLE [dbo].[XLX_PUR_InquiryOnline_Offer](
	[Id] [uniqueidentifier] NOT NULL,
	[FK] [uniqueidentifier] NULL,
	[InquiryMatList_Id] [uniqueidentifier] NULL,
	[MatBS_Guid] [uniqueidentifier] NULL,
	[MatBS_Code] [nvarchar](200) NULL,
	[MatBS_Name] [nvarchar](200) NULL,
	[MatId] [uniqueidentifier] NULL,
	[MatCode] [nvarchar](200) NULL,
	[MatName] [nvarchar](200) NULL,
	[Model] [nvarchar](1000) NULL,
	[Standard] [nvarchar](500) NULL,
	[Texture] [nvarchar](200) NULL,
	[MatUnit] [nvarchar](200) NULL,
	[MatUnit2] [nvarchar](200) NULL,
	[Equ] [decimal](10, 6) NULL,
	[Pressure] [nvarchar](200) NULL,
	[TaxRate] [decimal](10, 4) NULL,
	[Qty_Inquiry] [float] NOT NULL,
	[InquiryUnit] [nvarchar](50) NULL,
	[MatPrice] [float] NULL,
	[MatMoney] [float] NULL,
	[DeliveryDate] [nvarchar](20) NULL,
	[Remark] [nvarchar](500) NULL,
	[UpdDate] [datetime] NOT NULL,
	[RequestList_Id] [uniqueidentifier] NULL,
	[Specifi] [nvarchar](200) NULL,
	[Pattern] [nvarchar](200) NULL,
	[GoodsMatPrice] [float] NULL,
	[GoodsMatMoney] [float] NULL,
	[RequestCode] [nvarchar](200) NULL,
	[Request_Id] [uniqueidentifier] NULL,
	[MatSpec] [nvarchar](100) NULL,
	[TagNumber] [nvarchar](100) NULL,
)
