

CREATE TABLE [dbo].[PS_BID_PerformanceTB](
	[Id] [uniqueidentifier] NOT NULL,
	[Title] [nvarchar](500) NULL,
	[Code] [nvarchar](500) NULL,
	[CompanyName] [nvarchar](500) null,
	[CompanyId] uniqueidentifier null,
	[PassHumanName] [nvarchar](500) null,
	[PassHumanId] uniqueidentifier null,
	[PassHumanDepartment] [nvarchar](500) null,
	[PassHumanDuty] [nvarchar](500) null,
	[PerformanceTBDate] datetime null,
	[PayMoneyType] [varchar](100) null,
	[PayType] [varchar](100) null,
	[PayNature] [varchar](100) null,
	[PerformanceType] [varchar](100) null,
	[PayTo] [nvarchar](500) null,
	[PayToId] uniqueidentifier null,
	[IsInAdvance] [varchar](100) null,
	[BankCode] [nvarchar](500) NULL,
	[BankName] [nvarchar](500) NULL,
	[PerformanceAmount] money NULL,
	[PerformanceRemark] [nvarchar](500) NULL,
	[Memo] [nvarchar](1000) NULL,
	[Remark] [nvarchar](1000) NULL,
	[CompanyLeader] [nvarchar](500) NULL,

	[UpdHumId] [uniqueidentifier] NULL,
	[UpdHumName] [nvarchar](80) NULL,
	[UpdDate] [datetime] NULL,
	[RegDate] [datetime] NULL,
	[RegHumName] [nvarchar](80) NULL,
	[RegHumId] [uniqueidentifier] NULL,
	[OwnProjName] [nvarchar](255) NULL,
	[OwnProjId] [uniqueidentifier] NULL,
	[EpsProjId] [uniqueidentifier] NULL,
	[ApprHumId] [uniqueidentifier] NULL,
	[ApprHumName] [nvarchar](80) NULL,
	[ApprDate] [datetime] NULL,
	[Status] [tinyint] NULL,
	)