CREATE TABLE XLX_PUR_InquiryOnline_MatList(
	[Id] [uniqueidentifier] NOT NULL,
	[FK] [uniqueidentifier] NULL,
	[RequestList_Id] [uniqueidentifier] NULL,
	[MatBS_Guid] [uniqueidentifier] NULL,
	[MatBS_Code] [nvarchar](200) NULL,
	[MatBS_Name] [nvarchar](200) NULL,
	[MatId] [uniqueidentifier] NULL,
	[MatCode] [nvarchar](200) NULL,
	[MatName] [nvarchar](200) NULL,
	[Model] [nvarchar](1000) NULL,
	[Standard] [nvarchar](500) NULL,
	[Texture] [nvarchar](200) NULL,
	[MatUnit] [nvarchar](200) NULL,
	[MatUnit2] [nvarchar](200) NULL,
	[Equ] [decimal](10, 6) NULL,
	[Pressure] [nvarchar](200) NULL,
	[TaxRate] [decimal](10, 4) NULL,
	[Qty_Request] [float] NULL,
	[Qty_Inquiry] [float] NOT NULL,
	[InquiryUnit] [nvarchar](50) NULL,
	[Remark] [nvarchar](500) NULL,
	[RequestHumId] [uniqueidentifier] NULL,
	[RequestHumName] [nvarchar](80) NULL,
	[UpdDate] [datetime] NOT NULL,
	[Pattern] [nvarchar](200) NULL,
	[Specifi] [nvarchar](200) NULL,
	[RequestCode] [nvarchar](200) NULL,
	[Request_Id] [uniqueidentifier] NULL,
	[MatSpec] [nvarchar](100) NULL,
	[TagNumber] [nvarchar](100) NULL,
	[Bomfile_Id] [uniqueidentifier] NULL,
	[PlanDate] [datetime] NULL,
	[PartyB] [nvarchar](max) NULL,
	[MatPrice] [numeric](18, 4) NULL,
	[Zb_PartyB] [nvarchar](max) NULL,
	[Zb_MatPrice] [numeric](18, 4) NULL,
	[Zb_Num] [numeric](18, 4) NULL,
	[Zb_Total] [numeric](18, 4) NULL,
	[SuppJson] [nvarchar](max) NULL,
) 