CREATE TABLE [dbo].[SF_FK_RevenueRecognition](
	[Id] [uniqueidentifier] NOT NULL,
	[Code] [nvarchar](200) NULL,
	[Title] [nvarchar](200) NULL,
	[EpsProjectId] [uniqueidentifier] NULL,
	[EpsProjectName] [nvarchar](100) NULL,
	[YearMonth] [datetime] NULL,
	[UpdHumId] [uniqueidentifier] NULL,
	[UpdHuman] [nvarchar](80) NULL,
	[UpdDate] [datetime] NULL,
	[RegDate] [datetime] NULL,
	[RegHumName] [nvarchar](80) NULL,
	[RegHumId] [uniqueidentifier] NULL,
	[OwnProjName] [nvarchar](255) NULL,
	[OwnProjId] [uniqueidentifier] NULL,
	[EpsProjId] [uniqueidentifier] NULL,
	[ApprHumId] [uniqueidentifier] NULL,
	[ApprHumName] [nvarchar](80) NULL,
	[ApprDate] [datetime] NULL,
	[Status] [tinyint] NULL,
	[Memo] [nvarchar](4000) NULL,
	[ParentId] [uniqueidentifier] NULL,
	[IsNew] [nvarchar](200) NULL,
	[Version] [nvarchar](200) NULL
) 
CREATE TABLE [dbo].[SF_FK_RevenueRecognition_dtl](
	[Id] [uniqueidentifier] NOT NULL,
	[MasterId] [uniqueidentifier] NULL,
	[UpdDate] [datetime] NULL,
	[Memo] [nvarchar](4000) NULL,
	[Sequ] [int] NULL,
	[YearMonth] [datetime] NULL,
	[AmountType] [nvarchar](100) NULL,
	[ContractMoney] [float] NULL,
	[ContractChangeMoney] [float] NULL,
	[FinalContractMoney] [float] NULL,
	[ContractGetAmount] [float] NULL,
	[BudgetCost] [float] NULL,
	[BudgetRate] [float] NULL,
	[WorkCost] [float] NULL,
	[ProduceCost] [float] NULL,
	[Rate] [float] NULL,
	[MonthSchedule] [float] NULL,
	[MonthGetAmount] [float] NULL,
	[MonthRate] [float] NULL
) 

